### PR TITLE
Add emacs

### PR DESCRIPTION
**Pull request by PatrickRose**
Everyone knows that emacs is the best text editor. Right guys? Right?

This is a first blast at creating an emacs colour scheme, with possible mistakes all over the show.

### CODE REVIEW

**Comment by istinspring** [comment]
+1 for emacs.

**Comment by cloudbring** [comment]
These themes are beautiful. I would love to use them in Emacs / [syl20bnr/spacemacs](Spacemacs). Is there any way we could revisit this?

**Comment by PatrickRose** [comment]
Feel free to take the themes from my fork :-)

**Comment by daylerees** [comment]
Thanks Patrick. Sorry this took literally forever. I have way too many commitments it seems!

**Pull request merged**
